### ISSUE TITLE
Is Augmenter with deterministic=True thread safe?

### ISSUE THREAD

**Issue by JoshuaPiinRueyPan** [aleju/imgaug#125]
Hi,
   I want to apply your function to augment Videos.  The same video (the same batch) should be augmented in the same way.  Following function would be what I want.  My question is: can I call the following function in different thread?
```
def DataAugment(batchImages):
        aug = iaa.Sequential([  
                                iaa.Fliplr(0.5),
                                iaa.Crop(percent=(0, 0.1)),
                                ...
                            ])

        augDet = aug.to_deterministic()
        results = np.zeros(batchImages.shape,  batchImages.dtype)
        for i in range(batchImages.shape[0])
            results[i] = augDet.augment_image(batchImages[i])
        return results
```
  In my project, I load load data by many threads, and I want to augment the videos in such threads.  However, I found that after adding this function, the Tensorflow seems just die silently:  After several epoch, the whole program is not calculating at all (no GPU, CPU loading).  And no standard output from the loading threads since then.  Moreover, this program can't be stoped by Ctr+C (but can be killed).  Without calling the above function, everthing seems fine...

**Comment by JoshuaPiinRueyPan** [comment]
Finally, I found that after I eliminate the 'iaa.PiecewiseAffine' in the following code, everything work fine.  (The following code is obtained from your README, except for eliminating some unwanted augmenters.)  So the question would trun to: why 'iaa.PiecewiseAffine' cause dead lock?
```
def Augment(batchImages):
	sometimes = lambda aug: iaa.Sometimes(0.5, aug)
	augmentMethod = iaa.Sequential([
						iaa.Fliplr(0.5),
						iaa.SomeOf( (0, 5),
							    [
								iaa.Sharpen(alpha=(0, 1.0), lightness=(0.75, 1.5)), # sharpen images
								iaa.Emboss(alpha=(0, 1.0), strength=(0, 1.0)),
								iaa.SimplexNoiseAlpha(iaa.OneOf([
								    iaa.EdgeDetect(alpha=(0.3, 0.6)),
								    iaa.DirectedEdgeDetect(alpha=(0.3, 0.6), direction=(0.0, 1.0)),
								])),
								iaa.AdditiveGaussianNoise(loc=0, scale=(0.0, 0.05*255),
												 per_channel=0.5),

								iaa.Dropout( (0.0, 0.05), per_channel=0.5),
								iaa.Add((-10, 10), per_channel=0.5),
								iaa.AddToHueAndSaturation((-20, 20)),
								iaa.OneOf([
								    iaa.Multiply((0.5, 1.5), per_channel=0.5),
								    iaa.FrequencyNoiseAlpha(
									exponent=(-4, 0),
									first=iaa.Multiply((0.5, 1.5), per_channel=True),
									second=iaa.ContrastNormalization((0.5, 2.0))
								    )
								]),
								iaa.ContrastNormalization((0.6, 2.0), per_channel=0.5),
								iaa.Grayscale(alpha=(0.0, 0.8)),
								sometimes(iaa.PiecewiseAffine(scale=(0.01, 0.05))),
								sometimes(iaa.PerspectiveTransform(scale=(0.01, 0.1)))
							    ],
							    random_order=True
							)
					],
					random_order=True
				      )
```
Note: After I comment the above line: 'sometimes(iaa.PiecewiseAffine(scale=(0.01, 0.05))),', the augmenter seems still use 'PiecewiseAffine' as one of the augmenters.  Does this means that the 'PiecewiseAffine' is also included in the other augmenters shown above?  Is it the reason that cause dead lock?

**Comment by aleju** [comment]
You say that you are augmenting data in threads. Are you aware that this is to a degree pointless in python, as python threads do not use multiple cores? You have to use background processes to make proper use of multi-core architectures.
None of the augmenters are designed to be thread-safe, precisely because usually processes will be used instead of threads. For normal augmentation this will probably not be a problem, but when using determinism the result becomes undefined.

PiecewiseAffine is a wrapper around around scikit's warp function and PiecewiseAffineTransform. Not sure why these would cause any particular problems in multi-thread scenarios. Your problems sound like each thread is running into an error at some point and for some reason doesn't display that error. Once all threads have crashed, no data is generated any more and your training stalls.

Also, PiecwiseAffine is not a part of any other augmenter. It should not pop up once you comment out the respective line, though its always possible that a combination of other augmenters might end up looking visually similar.

**Comment by JoshuaPiinRueyPan** [comment]
I haven't aware that python do not use multiple cores, thanks for point it out.
