### ISSUE TITLE
ImportError: cannot import name augmenters

### ISSUE THREAD

**Issue by mathetes87** [aleju/imgaug#13]
Hi, when I try to import the augmenters file from imgaug root folder using iPython I get this error
 `ImportError: cannot import name augmenters`

Also, when I do the import `import augmenters as iaa` from the imgaug/imgaug folder, I get this error
```
       1 from __future__ import print_function, division, absolute_import
----> 2 from . import imgaug as ia
      3 from .parameters import StochasticParameter, Deterministic, Binomial, Choice, DiscreteUniform, Normal, Uniform
      4 from abc import ABCMeta, abstractmethod
      5 import random

ValueError: Attempted relative import in non-package
```

However, when importing from a python script it works fine

**Comment by aleju** [comment]
The "relative import" error is usually fixed by using `python -m filename` (where *filename* is without `.py`). Not sure if that works with iPython, as I usually just use scripts.
The first error is entirely dependent on where you saved the files and how you try to import them.
Also make sure to have an `__init__.py` in the directory.

**Comment by mathetes87** [comment]
It is working now. And working beautifully!
