### ISSUE TITLE
about the use of seq.to_deterministic()

### ISSUE THREAD

**Issue by sdalxn** [aleju/imgaug#162]
In some examples of keypoints and bounding boxes, there also are code segments like as:
 `seq_det = seq.to_deterministic()
    image_aug = seq_det.augment_images([rgb_img])[0]
    bbs_aug = seq_det.augment_bounding_boxes([bbs])[0]`
 I know that the function to_deterministic change the operation sequence "seq" from an random status into a deterministic status. I mean the operation order, each operation param all became solid. So the operation on a image will applied on the bounding box at the same time.

If I have a data set including 1000 pictures, and now I want to augment each picture using 64 methods. So I must  explicitly call  function  to_deterministic() 1000*64 times by code a loop. isn't it?

Is there  some other simple method?

**Comment by aleju** [comment]
Usually a loop is the best method.
You could also tile the 1000 images so that you get an array 64000 images, i.e. 64 times the first image, followed by 64 times the second image, and so on (and do the same with the bounding boxes). Though the loop is probably easier to read and less likely to cause out of memory errors.

**Comment by sdalxn** [comment]
@aleju 
Thanks a lot.
