### ISSUE TITLE
API for treating a bounding-box moved out of image boudary

### ISSUE THREAD

**Issue by jaelim** [aleju/imgaug#180]
I used the API (`remove_out_of_image()` and `cut_out_of_image()` in combination) to deal with a bounding-box moved out of image region; it worked but not producing a desirable result. Specifically it's related to `piecewiseAffine` on an object very close to the right image boundary which pushed the object partially out towards right (checked that upper left corner coordinates are set to (-1, -1)). 

After applying `bbs_aug.remove_out_of_image().cut_out_of_image()`, the upper left corners are set rather incorrectly to (0,0). 

Is this cleaning method works only for the linear translation augmentation (as demonstrated in the doc example)? Or is there some way to deal with this correctly?

**Comment by aleju** [comment]
Can you try `bbs_aug.remove_out_of_image(fully=True, partly=True).cut_out_of_image()` instead?
By default, `bbs_aug.remove_out_of_image()` currently only removes bounding boxes of which all corners are outside of the image plane (i.e. fully outside or `fully=True, partly=False`).

`PiecewiseAffine` should not change corners that are outside of the image. One has to be a bit cautious when using that augmenter. I think I have seen a case in the past where it produced a fairly wrong bounding box. It is also the by far slowest augmenter for keypoints and bounding boxes.

**Comment by aleju** [comment]
`cut_out_of_image()` removes parts of BBs that are outside of the image plane, thereby cutting them down to fit the image plane. Shouldn't be applied to BBs that are fully outside of the image plane - results will end up fairly broken.
`remove_out_of_image(fully=True, partly=False)` removes BBs that are fully and/or partially outside of the image plane.

So if I understand this correctly, the problem is that you have BBs with corners close to the right boundary and after application of PiecewiseAffine these corners may end up being replaced by corners at (-1, -1), leading to wrong bounding boxes and you want to fix them to look as expected? Fixing them after augmentation will probably be rather hard as it is not clear what they should look like. I guess you would have to iterate other the before/after bounding boxes and replace corners at (-1,-1) with the corners before augmentation. That again is problematic as other augmenters might have already moved these (-1,-1) to other locations.

I just pushed a fix to master that changes how PiecewiseAffine augments keypoints (and thereby bounding boxes). The corners should now not switch to (-1,-1) anymore. If that doesn't help you could also try decreasing the strength of `scale` in PiecewiseAffine.

**Comment by denisb411** [comment]
@aleju I think that `bbs_aug.remove_out_of_image()` or `bbs_aug.remove_out_of_image()` could be applied automatically because I lost a lot of time thinking that one of these process was done automatically and lost a lot of time debuging to find out why my training was breaking.
