### ISSUE TITLE
Gaussian blur is broken

### ISSUE THREAD

**Issue by KocsisV** [aleju/imgaug#211]
Hello!

I tried to use the GaussianBlur augmenter, but it seems to be broken. You can see my results in this image:
![image](https://user-images.githubusercontent.com/39518109/49223725-df098600-f3df-11e8-9bf3-ef2f07a21292.png)

The code that used:
```
imgaug.seed(random.randint(0,1000000))`
imgaug_sequence = imgaug.augmenters.Sequential([ imgaug.augmenters.GaussianBlur(sigma=(0,1)) ], random_order=True)
img = imgaug_sequence.augment_images(img)
```
img.shape is (640, 368, 3), dtype is uint8

imgaug version is 0.2.6, I installed it using pip3.

Am I doing something wrong?

**Comment by KocsisV** [comment]
If i change the sigma parameter to "sigma=10" I get the following:
![image](https://user-images.githubusercontent.com/39518109/49224429-b6828b80-f3e1-11e8-82f1-743b786baf9c.png)
Its only working on one axis and somehow gets black and white.

**Comment by KocsisV** [comment]
Found the problem:
It only works if I pass a 4D array/list (as described in the docs).

Please add a warning/exception to the augment_images function if it receives an incorrect format.

**Comment by aleju** [comment]
If you want to augment a single image, you have to use either `augment_image(image)` or `augment_images([image])[0]` or `augment_images(np.array([image]))[0]`.
An exception currently cannot be raised in `augment_images()` upon 3-dimensional inputs, because the library also accepts grayscale images of shape `(height, width)` (i.e. no channel axis) and hence the input can be of shape `(N, H, W)`.
However, a warning is currently raised if the input is 3-dimensional and the last axis has value `1` or `3`, which should catch most false inputs and should have appeared in your case. The warning might not be in the pypi version of the library yet -- not sure.
