### ISSUE TITLE
Different parameters for each image

### ISSUE THREAD

**Issue by kilsenp** [aleju/imgaug#217]
Hi, 
thanks for this great library.

Is there a best practice how to deal with parameters that change per image?
Specifically, I want to crop out an object given through a bounding box. So far I would probably get the augmenter by name and overwrite its parameters for every image.

Thanks

**Comment by aleju** [comment]
If you only want to get the image content of a bounding box you can also just do something like
```python
import imgaug as ia
image = ... load somehow ...
bb = ia.BoundingBox(x1=100, x2=150, y1=100, y2=150)
bb_image_area = bb.extract_from_image(image)
```
then `bb_image_area` contains the image content within the bounding box area.

If you want to achieve your goal via augmenters, then what you described is one possible way to do it. You could also just keep the stochastic parameter somewhere and update it. Something like the following should work:
```python
from imgaug import parameters as iap
from imgaug import augmenters as iaa

# rotate by 45deg
param = iap.Deterministic(45)
aug = iaa.Affine(rotate=param)
image_aug = aug.augment_image(image)

# rotate by 50deg
param.value = 50
image_aug = aug.augment_image(image)
```
and so on.
Similarly, you can save the augmenter in a variable and change its parameters directly, instead of first searching for it via name and only then changing its parameters. Saves the search.

Another way to do it is to reinstantiate the augmenters each time, though obviously that gives up a bit of performance. It also makes background/multicore augmentation and random order augmentation harder to achieve.
```python
def augment(image, rotate, crop_px):
    image = iaa.Affine(rotate=rotate).augment_image(image)
    image = iaa.Crop(px=crop_px).augment_image(image)
    return image

image = ... load image ...
image_aug = augment(image)
```

**Comment by kilsenp** [comment]
Okay, thanks!
