### ISSUE TITLE
Always getting black image

### ISSUE THREAD

**Issue by drbrown7** [aleju/imgaug#257]
I am trying to display a picture I pulled from a local folder. I have tried changing the data type of the numpy array, trying draw_grid instead of show_grid (which I have figured out doesn't display anything) and I've tried changing the show_grid parameters. No matter what I do the displayed image is always a black screen, if it displays at all. Sometimes python just freezes and I have to restart my computer. If you could help me figure out this problem I would really appreciate it.
![python black screen](https://user-images.githubusercontent.com/43002537/52529462-e55d8d80-2cbf-11e9-9fce-922c7f0362a6.png)

**Comment by aleju** [comment]
The points that I'm noticing:
* You start with an array of zeros via `np.zeros(...)`. If you show that array without changing its content, the resulting image will be black.
* If you add the loop and it still remains an array of zeros, it likely means that your loop does not execute, i.e. your `glob.glob(...)` statement finds no files that match the given path.
* The `np.zeros(...)` command should be changed to `np.zeros(..., dtype=np.uint8)`. You can also just make it a list via `T_data = []`, then append to it via `T_data.append(image)` and (optionally) convert it to an array later on via `T_data = np.array(T_data)`.
* The statement `T_data = (T_data*255).astype(np.uint8)` should be removed if using `cv2.imread()` as that function already returns `uint8`.
* You should change `image = cv2.imread(myFile)` to `image = cv2.imread(myFile)[:, :, ::-1]` as `cv2.imread` returns images in BGR colorspace instead of RGB.
* `show_grid()` should show a plot like in your screenshot. `draw_grid()` produces the same image as `show_grid()`, but returns it as an array instead of plotting it.
* I don't see anything in your script that should lead to a frozen python. It could take a while to execute if there are many images to load or speed of your hard drive is crawling slow. The `show_grid()` command could also sometimes take a while as 64 images of size 1080x1080 is a very large output image (roughly 8000x8000). Matplotlib might take a while to process that. However, it should not freeze.

Here is some example code that works fine for me when calling it from a directory that contains images:
```python
import imgaug.imgaug
from imgaug import augmenters as iaa
import cv2
import glob
import numpy as np

images = []
for image_fp in glob.glob("./*.jpg"):
    image = cv2.imread(image_fp)[:, :, ::-1]
    images.append(image)
images = np.array(images)

seq = iaa.Sequential([iaa.Fliplr(0.5), iaa.GaussianBlur((0, 3.0))])
seq.show_grid(images[0], cols=8, rows=8)
```

**Comment by drbrown7** [comment]
I think the freezing was caused by my image size (it was a few MB instead of a few tens of kB) but once I compressed them and ran your example script it all started working. Thanks for the help and advice!

**Comment by ramlakhanmandal** [comment]
I am a beginner and I am facing the same problem ( always getting black images ) but I didn't know what to do pls help it's a humble request to you all
