### ISSUE TITLE
Overwriting augment_segmentation_maps

### ISSUE THREAD

**Issue by kilsenp** [aleju/imgaug#261]
Hi,

the following case.
I want to flip a segmentation map left, right. However, the class labels change (from left_x to right_x and vice versa).
Currently, I found it impossible to implement without api changes.

My original idea was to just use the original implementation, but then overwrite augment_segmentation_maps and there change the non_empty_indices accordingly. In theory, the from_heatmaps method should build the Segmentation map than with switched class labels.

But I realized, that I cannot overwrite the augment_segmentation maps method because the Augmenter Base class defines a augment_segmentation_maps that calls directly augment_heatmaps.
So when I use Sequential, my augment_segmentation_maps  method is never called.

I would therefore suggest using a similar design as for all the other augmentation methods instead. 

I am of course also open for other suggestions how to implement this.

Thanks a lot!

**Comment by aleju** [comment]
The segmentation map augmentation is currently implemented in the quick and easy way of using heatmap augmentation as a proxy. That is planned to change so that segmentation map augmentation gets its own method. But it will take some time until that is finished, as such a method has to be addend to every augmenter (which includes testing and documentation).
It is also planned to add some kind of history to read out which random values were sampled for which image. That could be used here to estimate which images were flipped after executing the pipeline. But that is also not implemented yet, as the design of such a feature is rather difficult.

The best alternative currently is probably to take the flips out of the remaining augmentation pipeline and execute them manually afterwards. Then check if the segmentation map was changed and in that case also modify the labels.

**Comment by kilsenp** [comment]
Hi,
thank you for the response. I understand. Thanks for the alternative!

Best regards
