### ISSUE TITLE
[Documentation Question] Upsizing segmentation masks

### ISSUE THREAD

**Issue by austinmw** [aleju/imgaug#291]
I'm curious how a type uint segmentation mask is able to be resized larger. The only method that makes sense to me would be KNN, but the docs say, "Note that segmentation maps are handled internally as heatmaps (one per class) and as such can be resized using cubic interpolation." 

But wouldn't cubic interpolation fill intermediate pixels with float values instead of only using the integer values present in the original mask?

**Comment by aleju** [comment]
The segmentation map implementation is currently wrapped around heatmaps. The segmentation maps are converted from e.g. uint to floats when they are instantiated. One such heatmap is created per class in the segmentation map, leading to an `(H,W,C)` heatmap array with `C=number of classes`. Then the heatmaps are up/downscaled, e.g. via cubic interpolation. They use float values so that kind of works. When converting the segmentation map back to an integer array via `segmap.get_arr_int()`, the argmax along the channels `C` of the heatmap array is taken, so the float values are converted to integers.

Its not the most beautiful approach, but so far it looks like it works. It is though planned to make segmentation maps independent of heatmaps and heatmap augmentation. Then the upscaling would probably use nearest neighbour interpolation.

**Comment by austinmw** [comment]
Ah, got it, thanks!
