### ISSUE TITLE
BoundingBox misalignment for Affine+PerspectiveTransform case

### ISSUE THREAD

**Issue by killer9619** [aleju/imgaug#314]
In the following example, I feed an image along with a bounding box to an augmenter. The boxes misaligned with the image after transform.

I'd say if the original image is not cropped due during rotation, the bounding box seems to fit the image. However, if the original image is cropped, the bounding box looked weird in this case.

I am using imgaug 0.2.9

code:
https://gist.github.com/killer9619/ff0f949ae438c8351aac55c39724b798

original image with box:
![original](https://user-images.githubusercontent.com/17000685/57858916-88282980-7824-11e9-9f23-2deb206ae6a7.png)

transformed image with misaligned box
![misalignment](https://user-images.githubusercontent.com/17000685/57858940-9118fb00-7824-11e9-8b09-530c340fd516.png)

**Comment by aleju** [comment]
I think this to a large degree a case of affine rotation leading to weird bounding boxes.
The bounding box augmentation works by transforming the bounding box to its corner keypoints, augmenting these keypoints and then drawing a new bounding box around these augmented keypoints. When using rotation, the resulting bounding box often captures image parts that were previously not part of the (unaugmented) bounding box, leading to badly looking results.

Here is a visualization of your augmentation (before: left, after: right), which also shows the corner keypoints and adds some padded pixels at the side of the image to see the full bounding box:
![imgaug imshow((1200,_2400,_3))_4_rot](https://user-images.githubusercontent.com/11698516/57879764-78f1ad80-781d-11e9-8507-cdf6e25d2a8a.png)
Note how e.g. the paw on the left side is now fully inside the BB due to the lower left corner's rotation.

Here is the same image without rotation in `Affine`:
![imgaug imshow((1200,_2400,_3))_4_norot](https://user-images.githubusercontent.com/11698516/57879840-a3436b00-781d-11e9-94ac-f2325a5235fd.png)

Additionally to affine rotations, perspective transform will also cause similar distortions with equally bad-fitting bounding boxes after augmentation.
E.g. here is an image with strong perspective transformation, leading to the lower right BB corner to be augmented so far away that it isn't even visible anymore when using quite a lot of padding:
![imgaug imshow((1200,_2400,_3))_persp](https://user-images.githubusercontent.com/11698516/57880395-ebaf5880-781e-11e9-967e-84f053f7fd0f.png)


In general, bounding boxes are not that easy to augment well. Pretty well working should be all augmentations that only affect the image, horizontal/vertical flips, rotations by multiples of 90°, crop, pad, affine scaling and translation and elastic transformations with low sigmas. Affine rotations, perspective transformations, piecewise affine and elastic transformations (with high sigma) only work decently if fairly low values are chosen as hyperparameters so that they don't have much effect.

Code for the visualizations:
```python
import random
import imageio
import imgaug as ia
import numpy as np
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage
from imgaug.augmentables.kps import KeypointsOnImage, Keypoint
from imgaug import augmenters as iaa

ia.imgaug.seed(15)
random.seed(5)

def preprocess_train(im, boxes):
    #build boxes as imgaug format
    imgboxes = BoundingBoxesOnImage.from_xyxy_array(boxes, im.shape)
    kps = [(boxes[0][0], boxes[0][1]),  # x1y1
           (boxes[0][2], boxes[0][1]),  # x2y1
           (boxes[0][2], boxes[0][3]),  # x2y2
           (boxes[0][0], boxes[0][3])]  # x1y2
    imgkps = KeypointsOnImage([Keypoint(x=x, y=y) for x, y in kps], shape=im.shape)
    print("kps", imgkps)

    #invoke img aug
    seq = iaa.Sequential([
            #default augmentation
            iaa.Resize({"width": 576, "height": 576}),
            iaa.Sequential(
            #random augmentation
            [
                iaa.Affine(translate_percent={"x": (-0.25, 0.25), "y":(-0.25, 0.25), }, scale=(0.75, 1.25), rotate=(0, 25), mode='constant'),
                #iaa.Affine(translate_percent={"x": (-0.25, 0.25), "y":(-0.25, 0.25), }, scale=(0.75, 1.25), mode='constant'),
                iaa.PerspectiveTransform(scale=(0.01, 0.25)),
            ], random_order=True),

        ],
        random_order=False)


    #apply
    image_aug, boxes_aug, kps_aug = seq(image=im, bounding_boxes=imgboxes, keypoints=imgkps)
    image_aug = ia.imresize_single_image(image_aug, im.shape[0:2])
    boxes_aug = boxes_aug.on(image_aug)
    kps_aug = kps_aug.on(image_aug)

    #go back to np
    boxes = boxes_aug.to_xyxy_array(dtype=np.int)

    #image type transform
    #image_aug = image_aug.astype(np.float) / 255.

    #display
    amount = 300
    im_pad = ia.pad(im, top=amount, right=amount, bottom=amount, left=amount)
    image_aug_pad = ia.pad(image_aug, top=amount, right=amount, bottom=amount, left=amount)
    imgboxes_pad = imgboxes.shift(top=amount, left=amount)  #.on(im_pad)
    boxes_aug_pad = boxes_aug.shift(top=amount, left=amount)  #.on(image_aug_pad)
    imgkps_pad = imgkps.shift(x=amount, y=amount)  #.on(im_pad)
    kps_aug_pad = kps_aug.shift(x=amount, y=amount)  #.on(image_aug_pad)

    print(boxes_aug)
    print(im_pad.shape, image_aug_pad.shape)
    ia.imshow(np.hstack([
        imgboxes_pad.draw_on_image(
            imgkps_pad.draw_on_image(im_pad, size=11),
            size=2),
        boxes_aug_pad.draw_on_image(
            kps_aug_pad.draw_on_image(image_aug_pad, size=11),
            size=2)
    ]))

    return image_aug, boxes

img = imageio.imread('https://t1.ea.ltmcdn.com/en/images/2/3/0/img_names_for_golden_retrievers_32_600.jpg')
boxes = np.array((100, 59, 502, 547), ).reshape(1, 4)   #x1y1x2y2
#boxes = np.array((100, 159, 302, 347), ).reshape(1, 4)   #x1y1x2y2

#while True:
preprocess_train(img, boxes, )

```

**Comment by killer9619** [comment]
Hello, thanks for the replying.
I understand the bounding box can't be strictly aligned with the original image after perspective transform or rotate. However, I am more concerned about the image portion being cropped during the operations but the bounding box didn't respect such operation.

I meant the painted region in the image.
![marked](https://user-images.githubusercontent.com/17000685/57899578-374e1a80-7890-11e9-9ee6-36a9cb2aebdc.jpg)

The bounding box included a large background region, and it will confuse the network eventually if I trained with the images. 

To me, the following options are anticipated:
1. the best case would be not cropping the image during the augments, I anticipate this only happen after all transforms are done.
2. cut the size of the bounding box as what has done to the image.

I don't know if this is a trivial change, or I'd like some advice that I can work around this problem.

Thanks again for the replying and the great work!

**Comment by killer9619** [comment]
Also, I got this problem only when I do PerspectiveTransform before the Affine(rotation). If I change the order, the bounding box seems to fit the image much better. IMO, changing the order will affect the result doesn't make much sense.

**Comment by aleju** [comment]
> the best case would be not cropping the image during the augments, I expected this only happen after all transforms are done.

This is currently not part of the library and would be very non-trivial to implement. It would only work for *consecutive* augmentations that can be reduced to simple transformation matrices (which I think is only the case for Affine, PerspectiveTransform and Fliplr/Flipud). If there would be any other augmentation in between, the image after applying the previous transformation matrix would have to be resolved in order to get the augmentation's input, i.e. the current pixel values.
Keeping alternatively the full image after every augmentation and only cropping in the very end has the major disadvantage that it could lead to gigantic intermediary images, e.g. when applying strong zoom-in via affine scaling.

> cut the size of the bounding box as what has done to the image.

That is not yet part of the library. Currently you could apply each augmenter on its own and then call `BoundingBoxesOnImage.clip_out_of_image()` after Affine/PerspectiveTransform, which would remove all BB parts outside of the image plane.

> IMO, changing the order will affect the result doesn't make much sense.

That is currently a desired feature of the library as it significantly increases the space of the generated augmentations. E.g. applying first gaussian noise and then sharpening will also sharpen the edges around the noise pixels. Doing it the other way round will only sharpen the image content. These are two very different transformations that a model has to learn to be invariant towards.

**Comment by killer9619** [comment]
OK, I understood this is the limitation of the library. I'll work around this, thanks for replying! I'll close this issue.
