### ISSUE TITLE
parallel imread()

### ISSUE THREAD

**Issue by linfan68** [aleju/imgaug#357]
I'm trying to build an data pipeline using imgaug. And in the document it mentioned clearly we should try to avoid imgaug with other multi-core/parallel processing pipelines.
However, I cannot find a easy way to distribute imread() to multiple CPU cores. The input source of imgaug is numpy arrays. Did I missed something? Do I need another data parallel framework (like tensorpack) to feed imgaug in order to make imread running on multiple cores?

**Comment by aleju** [comment]
imgaug doesn't have an `imread` function. Do you mean `imageio.imread()`? I don't think that function automatically uses multiple CPU cores.

You can always load the images in multiple processes, join them in one and then augment them again in multiple processes via imgaug's multicore methods. You can also use imgaug directly in a dataloading pipeline. It is discouraged to do that, because you run the risk of getting the same augmentations in each subprocess (applied to different images). That is because your augmentation pipeline is copied from the main process into the child processes and that copy includes the seeds for the random number generators. If you reseed each augmentation pipeline once per subprocess (using different seeds), this would not be an issue. Some dataloading pipelines allow you to define an initialization function that is called after the subprocess has been created. Such a function could be used after initialization.

Technically, it's also not _wrong_ to skip the reseeding and accept getting the same augmentations in each subprocess. It might however affect your training negatively and could e.g. slow it down or have a small negative effect on the generalization capability. (This is speculation though, never tested it explicitly. I would expect any such issue -- if it exists -- to be less significant for larger batch sizes.)

**Comment by linfan68** [comment]
Thanks! I'm using dataflow from tensorpack for data pipeline. And after reading imgaug document I'm not sure how safe it is to drive imgaug with another parallel framework. As you explained I believe the impact should be minor, since normally during training we'll also shuffle data points within an epoch, so the final impact will be same augmentation applied to different images.
