### ISSUE TITLE
CropToFixedSize position issue

### ISSUE THREAD

**Issue by r0f1** [aleju/imgaug#438]
Consider the following piece of code:

```python
import numpy as np
np.set_printoptions(linewidth=160)
image = np.arange(20*20).reshape((20,20))

xs, ys, w, h = [0,10,15]*3, sorted([0,10,15]*3), 5, 5
res = [image[slice(y, y+h), slice(x, x+w)] for x, y in zip(xs, ys)]
```
<img width="668" alt="Unbenannt" src="https://user-images.githubusercontent.com/7324891/65420716-25fab900-de02-11e9-83c6-07cfc2ecb891.PNG">
<img width="156" alt="Unbenannt2" src="https://user-images.githubusercontent.com/7324891/65420717-26934f80-de02-11e9-95fa-5b38eedd0506.PNG">

This code splits up an image, into 9 smaller subimages.
Now look at the following piece of code:

```python
from imgaug.augmenters import CropToFixedSize
augs = [
    CropToFixedSize(width=5, height=5, position="right-bottom"),
    CropToFixedSize(width=5, height=5, position="center-bottom"),
    CropToFixedSize(width=5, height=5, position="left-bottom"),
    CropToFixedSize(width=5, height=5, position="right-center"),
    CropToFixedSize(width=5, height=5, position="center-center"),
    CropToFixedSize(width=5, height=5, position="left-center"),
    CropToFixedSize(width=5, height=5, position="right-top"),
    CropToFixedSize(width=5, height=5, position="center-top"),
    CropToFixedSize(width=5, height=5, position="left-top")
]
for a in augs:
    print(a.augment_image(image))
```

This piece will produce exactly the same result. I am confused however with the parameters of passed to the `position` argument. E.g. `"right-bottom"` is not in the bottom right, but rather in the top left. `"cencer-bottom"` is in the center at the top. etc. You can maybe explain why that is?

**Comment by aleju** [comment]
The `position` parameter for `PadToFixedSize` and `CropToFixedSize` currently defines in which area the pixels are modified. So, for `position="right-bottom"` `PadToFixedSize` would add new pixels at the bottom right and `CropToFixedSize` would remove pixels at the bottom right (to be more precise: it would remove pixels only from the bottom and right sides of the image and none from the top and left sides).

That means that the parameter is currently a bit unintuitive due to it being aligned with `PadToFixedSize`. Might make sense to change that.

**Comment by r0f1** [comment]
Ahh, I see, thanks for clearing that up. 

After reading you explaination, I guess there is not need to change how the parameter works. I'd say that consistency is more important. Updating the docs and mentioning the behaviour would be nice :) 

Thanks.
