### ISSUE TITLE
Changes : Review documentation style

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#5]
I have added (some) documentation for the Augmenter and Noop classes in the augmenters.py file.

Review the changes in [My fork](https://github.com/SarthakYadav/imgaug) and make suggestions.

This is just a glimpse. Much work will be needed on documentation (as more often than not I am not quite sure what a parameter signifies, etc).

**Comment by aleju** [comment]
Looks fine to me.

Notes:

1) Determinism means that the random state will be saved before augmenting images and then (after augmenting them) the random state will be reset to the saved one. So at the start of each augmentation the random state will always be the same one. E.g. if a non-deterministic horizontal flipper receives batches of each two images, it may sometimes flip the first image, sometimes the second, sometimes both or none. A deterministic horizontal flipper might always flip the first image and never the second (or always both, or always none). That is useful to transform different lists/arrays of images in the same way, e.g. images and their associated heatmaps.

2) The augment_images function will usually receive a single 4d numpy arrays, but can also handle a list of 3d numpy arrays. That is useful for images with different heights/widths.

**Comment by aleju** [comment]
And hooks could be described as a class to dynamically interfer with an augmentation process. E.g. deactivate specific augmenters in an augmentation sequence (but don't deactivate them permanently, only for one run), or change each image in a specific way before it enters augmenter X. I guess I will have to write some documentation for it at some point.

**Comment by SarthakYadav** [comment]
That's a lot of details!!! No way I could've figured that out on my own. I'll continue to scorch the code.
Also, considering how large a single module is, (the augmenters.py has so many classes) and after adding documentation, it will grow even more, are you considering breaking things up into separate files?

**Comment by aleju** [comment]
I have thought about that. But I want to keep things simple for the user so that they can just use `iaa.<AugmenterName>`, instead of having to memorize subcategories and then use `iaa.<subcategory>.<AugmenterName>` (which also has the disadvantage that once you have defined the subcategories you can hardly change them any more, as otherwise tons of code will break). The only "clean" way that I know to achieve that and still split up the files in the project would be to "merge" them in the `__init__.py`. But that again has the disadvantage that when people want to look at the code to find out how things work exactly, they will be confused where the classes are that they import, because import statements and file structure in the repository don't match any more.
So for now I plan to just keep it this way until the files become unbearably large. Then I guess switch to the init file method, unless something better pops up.

**Comment by SarthakYadav** [comment]
Yeah. Makes sense.
