### ISSUE TITLE
Flip.Fliplr does not modify bounding boxes appropriately

### ISSUE THREAD

**Issue by mathild7** [aleju/imgaug#521]

**Comment by UrwLee** [comment]
yes，i met the same situation

**Comment by aleju** [comment]
If you encounter problems with unaligned transformations, the most likely reason is one of the two:
* Wrong `shape` attribute: If you use `BoundingBoxesOnImage` to represent your bounding boxes, make sure that the `shape` attribute really matches the image shape. (This problem can be spotted in `Fliplr` by bounding boxes being flipped, but to the wrong positions.)
* Unaligned random samples: Call the augmenter(s) via `__call__` or `augment` with both images and bounding boxes. E.g. use `aug = iaa.Fliplr(0.5); images_aug, bbs_aug = aug(images=images, bounding_boxes=bbs)` instead of manually calling `aug.augment_images(images)` and `aug.augment_bounding_boxes(bbs)`. Using a single augmentation call decreases the probability that a missing/misplaced `to_deterministic()` call will lead to unaligned samples from the random number generator between augmentation calls. (This problem can be spotted in `Fliplr` by bounding boxes sometimes not being flipped when images are flipped -- and vice versa.)

**Comment by AhmedGhazale** [comment]
I have the same problem and I tried every thing and I still couldn't get it to work can @aleju can you show a example that work?

**Comment by aleju** [comment]
Below is an example script. Just replace `image=image` with `images=images` (where the variable `images` is e.g. a list of arrays) and turn `bbs` into a list of lists of `BoundingBox` if you want to augment a whole batch instead of a single image.

```python
import imageio
import numpy as np

import imgaug as ia
import imgaug.augmenters as iaa


def main():
    image = imageio.imread(
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/"
        "Cinnamomum_verum_spices.jpg/800px-Cinnamomum_verum_spices.jpg"
    )
    bb = ia.BoundingBox(x1=380, y1=290, x2=630, y2=420)
    bbs = [bb]

    image_aug, bbs_aug = iaa.Fliplr(1.0)(image=image, bounding_boxes=bbs)

    image_before = ia.BoundingBoxesOnImage(
        bbs, shape=image.shape).draw_on_image(image)
    image_after = ia.BoundingBoxesOnImage(
        bbs_aug, shape=image_aug.shape).draw_on_image(image_aug)

    ia.imshow(np.hstack([image_before, image_after]))


if __name__ == "__main__":
    main()
```

![fliplr](https://user-images.githubusercontent.com/11698516/73686060-962a1d00-46c7-11ea-8cfb-ae74fccc364b.png)
