### ISSUE TITLE
Random seed / state examples?

### ISSUE THREAD

**Issue by cclaan** [aleju/imgaug#555]
I'm having trouble setting a random state or seed to create a reproducible augmenter. Using to_deterministic() does work, but I'm working with someone else's code so it would be difficult to use. 
Is it possible to set a seed or state and expect future calls to some augmenter to be repeatable?  ( assuming none have used to_deterministic() internally ) 
I've seen a few issues here regarding this, but some are out of date and don't work for me. 
I've attached a very basic notebook where I can't seem to get a reproducible augmentation for a single Affine rotation. The first time I use the seed everything seems to work, but after plotting the images and re-running, the output has changed. I'm assuming I've done something stupid, but I've tried several methods of setting the seed and haven't had luck. 
Thanks

[imgaug seed.ipynb.zip](https://github.com/aleju/imgaug/files/4031833/imgaug.seed.ipynb.zip)

**Comment by aleju** [comment]
You have to change your plotting loops from
```python
for img, img2, img3 in zip(output, output2, output3):
    figure(figsize=(11,5))
    ...
```
to
```python
for img1, img2, img3 in zip(output, output2, output3):
    figure(figsize=(11,5))
    ...
```
i.e. `img` to `img1`. Otherwise you are overwriting your input image. Took me a while to spot that one too. :smiley:

Regarding the seeding, there are quite a few options:
* `Affine(.., random_state=123)` sets that augmenter's initial seed to `123`. Every augmentation call will depend indirectly on that seed (but each consecutive augmentation call will still produce different results). This is the best way to set augmenter-specific seeds.
* `augmenter = Affine(...); augmenter.seed(123)` sets the augmenter's seed after its creation to `123` (and also seeds the children with derived seeds).
* `imgaug.seed(123)` is an alias for `imgaug.random.seed(123)`.
* `imgaug.random.seed(123)` re-creates the global RNG with seed `123`. All augmenters initialized without an explicit `random_state=...` depend on this. But the seed should be set once at the start of the script, because the global RNG is currently re-created each time (so augmenters created before the call might point to an older global RNG).
* `imgaug.random.RNG.set_state_(<state>)` sets internal state dictionary of the RNG's bit generator to the given one. See numpy's bit generators for details. That's a very low level function. Usually not necessary to call.
* `numpy.seed(123)` sets the seed of numpy. imgaug initially derives its first seed from numpy. So if numpy's seed is set before any augmenter is created, that should also seed imgaug.

python's `random` module is not used by imgaug, so setting its seed has no effect.

You also used `to_deterministic()`. That method is used to make sure that consecutive calls of augmentation functions produce the same samples. E.g. if Affine produced the rotations `50.5` (image 1), `-32.3` (image 2), `16.6` (image 3) at the first augmentation (batch 1), it will again produce `50.5` (image 1), `-32.3` (image 2), `16.6` (image 3) at the second augmentation call (batch 2). This is useful to e.g. augment two sets of images in identical ways or to augment images and corresponding segmentation maps in the same way. Such identical augmentation is handled automatically by something like `augmenter = Affine(...); images_aug, segmaps_aug = augmenter(images=<images>, segmentation_maps=<segmaps>, ...)`, so in most cases the method doesn't have to be called explicitly anymore.

**Comment by cclaan** [comment]
Thanks for debugging my dumb mistake, and thanks for the thorough explanation, it's very helpful. 
This notebook was made to debug a more complex code path, and now I understand why the other setup wasn't working. I didn't realize augmenters created before calling imgaug.seed(123) would not be affected since they hold on to their RNG. 

So the API I was looking for was `my_affine.reseed(123) ` 

I don't suppose there is something like `imgaug.reseed_all(123)` that would prevent me from having to dig and discover all the augmenters being used in the subsequent calls after my re-seeding?

**Comment by aleju** [comment]
> I don't suppose there is something like imgaug.reseed_all(123) that would prevent me from having to dig and discover all the augmenters being used in the subsequent calls after my re-seeding?

No, there is currently no global registry of all created augmenters. I think one could monkeypatch `imgaug.augmenters.meta.Augmenter.__init__()` to create such a registry though. Currently, all augmenters should call that function. `reseed_all()` would then just iterate over that list and call something like `augmenter.seed(base_seed + i)` on each augmenter.

In the future, `imgaug.random.seed()` should again seed the global RNG in-place instead of creating a new one. That was the case previously and only dropped because numpy's new `Generator` interface doesn't seem to offer in-place seeding anymore. So that functionality would probably have to be implemented by creating a state dictionary and setting that in-place. Not sure though if that would fully work or cause unexpected issues somewhere.
