### ISSUE TITLE
PiecewiseAffine optimization when only using keypoints - no image

### ISSUE THREAD

**Issue by AmitMY** [aleju/imgaug#621]
I have the following list of key points that are not bound to an image:
![image](https://user-images.githubusercontent.com/5757359/75089965-c8ac9480-5566-11ea-883f-1d1e1cfb1e06.png)

I would like to create some distorted humans, like this one:
![image](https://user-images.githubusercontent.com/5757359/75089980-ef6acb00-5566-11ea-8cfe-eb164673ce3b.png)

To create this distorted human, I used (among other augmentations) the `PiecewiseAffine` augmentation. 
But, I find it to be too slow for my needs.
 
I was thinking, as my use case is just to augment 100 key points, rather than hundreds of thousands of pixels, that there might be a faster algorithm to apply this transformation.

Code:
```py
import imgaug.augmenters as iaa
from imgaug.augmentables import Keypoint, KeypointsOnImage

kps = KeypointsOnImage([
    Keypoint(x=65, y=100),
    Keypoint(x=75, y=200),
    Keypoint(x=100, y=100),
    Keypoint(x=200, y=80)
], shape=(256, 256))

seq = iaa.Sequential([
    iaa.PiecewiseAffine(scale=(0.01, 0.05)),  # Distort keypoints
])

# Augment keypoints
kps_aug = seq(keypoints=kps)

for i in range(len(kps.keypoints)):
    before = kps.keypoints[i]
    after = kps_aug.keypoints[i]
    print("Keypoint %d: (%.8f, %.8f) -> (%.8f, %.8f)" % (i, before.x, before.y, after.x, after.y))
```

**Comment by aleju** [comment]
The keypoint augmentation in `PiecewiseAffine` currently projects each keypoint onto an image and warps that, instead of only operating on the raw coordinates. This inefficient method was used, because scikit-image's piecewise affine warping seemed to not perform the same transformation for images and keypoints, leading to misalignments for large scale values.
As you only want to transform keypoints, it should be fine to use the method based on coordinate-warping though. You essentially just have to overwrite `_augment_keypoints_by_samples()` in `PiecewiseAffine`. See an example script below.

```python
import numpy as np

import imgaug as ia
import imgaug.augmenters as iaa


class PiecewiseAffineKP(iaa.PiecewiseAffine):
    def _augment_keypoints_by_samples(self, kpsois, samples):
        result = []

        for i, kpsoi in enumerate(kpsois):
            transformer = self._get_transformer(
                kpsoi.shape, kpsoi.shape, samples.nb_rows[i],
                samples.nb_cols[i], samples.jitter[i])

            if transformer is None or len(kpsoi.keypoints) == 0:
                result.append(kpsoi)
            else:
                coords = kpsoi.to_xy_array()
                coords_aug = transformer.inverse(coords)
                result.append(
                    ia.KeypointsOnImage.from_xy_array(
                        coords_aug,
                        shape=kpsoi.shape
                    )
                )

        return result


def main():
    kps = ia.KeypointsOnImage([
        ia.Keypoint(x=10.5, y=12.2),
        ia.Keypoint(x=10.5, y=22.2),
        ia.Keypoint(x=10.5, y=32.2),
        ia.Keypoint(x=10.5, y=42.2),
        ia.Keypoint(x=32.0, y=5.7),
        ia.Keypoint(x=32.0, y=15.7),
        ia.Keypoint(x=32.0, y=25.7),
        ia.Keypoint(x=32.0, y=35.7),
    ], shape=(50, 75))
    kps_aug = PiecewiseAffineKP(0.1)(keypoints=kps)

    img = np.full((50, 75, 3), 255, dtype=np.uint8)
    border = np.full((50, 1, 3), 0, dtype=np.uint8)
    ia.imshow(
        np.hstack([
            kps.draw_on_image(img),
            border,
            kps_aug.draw_on_image(img)
        ])
    )


if __name__ == "__main__":
    main()
```

![piecewise_kps](https://user-images.githubusercontent.com/11698516/75094364-a3ca1880-558a-11ea-8cbb-8f18493c9732.png)

**Comment by AmitMY** [comment]
Thank you very much.
This is the best response I've every gotten to an issue!

And I managed to run everything.
![image](https://user-images.githubusercontent.com/5757359/75095580-0c22f500-559f-11ea-9e01-831baa9f7b97.png)

If I may ask before I close this, why not just make this behavior the default when no image is provided?

**Comment by aleju** [comment]
Until recently the input types (e.g. images, keypoints) were augmented independently instead of batchwise. So there was no reliable way of knowing during keypoint augmentation whether there had been images augmented beforehand for the same batch. Since the latest version that is possible (as augmentation happens batchwise now), but the old style of input type-wise augmentation can still be used and is probably still being used in many scripts. In some cases it actually has to be used (e.g. multiple images per example that should be augmented in the same way.) Detecting whether only keypoints are being augmented would not be trivial due to this situation and could lead to false positives.

There is also the factor that augmenting keypoints only is probably a very rare use case. Most users augment images + keypoints, I guess. These would not profit from a separate keypoint-only method.

The really clean solution would be to rewrite PiecewiseAffine so that it performs proper coordinate augmentation and is faster for images. Currently it is one of the slowest augmenters, not only for keypoints.

**Comment by AmitMY** [comment]
Thank you for the detailed explanation.
If so, only one problem remains!

When I'm using the proper augmentation I get the following good output:
![image](https://user-images.githubusercontent.com/5757359/75096539-37124680-55a9-11ea-9ae4-b71e9df79846.png)

But when I use your suggested code, I guess whatever "moves" beyond the bounding box is zeroed out, so I get:
![image](https://user-images.githubusercontent.com/5757359/75096554-5ad58c80-55a9-11ea-8575-715ecea055e6.png)

I can't replicate this on Google Colab, but I can locally:
Here is the colab:
https://colab.research.google.com/drive/1axrROA251lQolunKMnzZ1Z5YvpCnooyU

```py
import imgaug as ia
import imgaug.augmenters as iaa

class PiecewiseAffineKP(iaa.PiecewiseAffine):
    def _augment_keypoints_by_samples(self, kpsois, samples):
        result = []

        for i, kpsoi in enumerate(kpsois):
            transformer = self._get_transformer(
                kpsoi.shape, kpsoi.shape, samples.nb_rows[i],
                samples.nb_cols[i], samples.jitter[i])

            if transformer is None or len(kpsoi.keypoints) == 0:
                result.append(kpsoi)
            else:
                coords = kpsoi.to_xy_array()
                coords_aug = transformer.inverse(coords)
                result.append(
                    ia.KeypointsOnImage.from_xy_array(
                        coords_aug,
                        shape=kpsoi.shape
                    )
                )

        return result

import imgaug.augmenters as iaa
from imgaug.augmentables import Keypoint, KeypointsOnImage

kps = KeypointsOnImage([
    Keypoint(x=272.27900000, y=74.29500000),
    Keypoint(x=278.17900000, y=191.85600000),
    Keypoint(x=115.58800000, y=187.90400000),
    Keypoint(x=0.00000000, y=446.45500000),
    Keypoint(x=154.84000000, y=293.72600000),
], shape=(447, 545))

seq = iaa.Sequential([
    PiecewiseAffineKP(scale=(0.01, 0.05)),  # Distort keypoints
])

# Augment keypoints
kps_aug = seq(keypoints=kps)

for i in range(len(kps.keypoints)):
    before = kps.keypoints[i]
    after = kps_aug.keypoints[i]
    print("Keypoint %d: (%.8f, %.8f) -> (%.8f, %.8f)" % (i, before.x, before.y, after.x, after.y))
```


Local output:

> Keypoint 0: (272.27900000, 74.29500000) -> (253.20989990, 71.86281586)
> Keypoint 1: (278.17900000, 191.85600000) -> (269.88153076, 185.57524109)
> Keypoint 2: (115.58800000, 187.90400000) -> (113.75486755, 185.18766785)
> Keypoint 3: (0.00000000, 446.45500000) -> (-1.00000000, -1.00000000)
> Keypoint 4: (154.84000000, 293.72600000) -> (157.20280457, 295.84243774)

Google Colab output:

> Keypoint 0: (272.27900000, 74.29500000) -> (281.00000000, 69.00000000)
> Keypoint 1: (278.17900000, 191.85600000) -> (274.00000000, 188.00000000)
> Keypoint 2: (115.58800000, 187.90400000) -> (116.00000000, 182.00000000)
> Keypoint 3: (0.00000000, 446.45500000) -> (0.00000000, 446.00000000)
> Keypoint 4: (154.84000000, 293.72600000) -> (151.00000000, 290.00000000)

**Comment by AmitMY** [comment]
So to sum up: (I've edited too much)
The code you provided works wonderfully with imgaug 0.2.9, but not with imgaug 0.4.0
Reproduction: https://colab.research.google.com/drive/1axrROA251lQolunKMnzZ1Z5YvpCnooyU

The bug is when a coordinate becomes negative, it resets to (-1, -1)

**Comment by aleju** [comment]
The code only seems to work with 0.2.9, because in that version `PiecewiseAffine` never calls `_augment_keypoints_by_samples()`.

After a bit of debugging it seems like `transformer.inverse(coords)` can return `(-1, -1)`. So the error is in scikit-image. I guess that was one of the reasons why I switched to image-based keypoint augmentation. Had already forgotten about that problem.

As scikit-image's method cannot be changed, the only way to deal with this issue here is probably to either reset the `(-1, -1)` keypoints to their old coordinates or to remove them. The code below resets them, which is easier to do:
```python
import numpy as np

import imgaug as ia
import imgaug.augmenters as iaa


class PiecewiseAffineKP(iaa.PiecewiseAffine):
    def _augment_keypoints_by_samples(self, kpsois, samples):
        result = []

        for i, kpsoi in enumerate(kpsois):
            transformer = self._get_transformer(
                kpsoi.shape, kpsoi.shape, samples.nb_rows[i],
                samples.nb_cols[i], samples.jitter[i])

            if transformer is None or len(kpsoi.keypoints) == 0:
                result.append(kpsoi)
            else:
                coords = kpsoi.to_xy_array()
                coords_aug = transformer.inverse(coords)
                kpsoi_aug = ia.KeypointsOnImage.from_xy_array(
                    coords_aug,
                    shape=kpsoi.shape
                )

                # replace keypoints that are outside of the image with their
                # old coordinates
                kpsoi_aug.keypoints = [
                    kp if (
                        0 <= kp.x < kpsoi_aug.shape[0]
                        and 0 <= kp.y < kpsoi_aug.shape[1]
                    ) else kp_old
                    for kp, kp_old
                    in zip(kpsoi_aug.keypoints, kpsoi.keypoints)
                ]

                result.append(kpsoi_aug)

        return result


def main():
    kps = ia.KeypointsOnImage([
        ia.Keypoint(x=10.5, y=12.2),
        ia.Keypoint(x=10.5, y=22.2),
        ia.Keypoint(x=10.5, y=32.2),
        ia.Keypoint(x=10.5, y=42.2),
        ia.Keypoint(x=32.0, y=5.7),
        ia.Keypoint(x=32.0, y=15.7),
        ia.Keypoint(x=32.0, y=25.7),
        ia.Keypoint(x=32.0, y=35.7),
    ], shape=(50, 75))
    kps_aug = PiecewiseAffineKP(0.2)(keypoints=kps)

    print(kps_aug.to_xy_array())

    img = np.full((50, 75, 3), 255, dtype=np.uint8)
    border = np.full((50, 1, 3), 0, dtype=np.uint8)
    ia.imshow(
        np.hstack([
            kps.draw_on_image(img),
            border,
            kps_aug.draw_on_image(img)
        ])
    )


if __name__ == "__main__":
    main()

```

**Comment by AmitMY** [comment]
Your help has been tremendous. Thank you very much.
