### ISSUE TITLE
Inconsistent behaviour of imgaug

### ISSUE THREAD

**Issue by pritul2** [aleju/imgaug#698]
### For Fliplr 
First time When I applied the fliplr as follows
![image](https://user-images.githubusercontent.com/41751718/87153642-6cf46500-c2d5-11ea-8741-234749ae346d.png)
-------------------------------------------------------------------------------------------
Second time I again rerun the fliplr then it works perfectly fine
![image](https://user-images.githubusercontent.com/41751718/87153688-7da4db00-c2d5-11ea-91a0-c010304b232a.png)
-------------------------------------------------------------------------------------------
Third time I changed the value of p=1.0 then I do not observe any change
![image](https://user-images.githubusercontent.com/41751718/87153729-8dbcba80-c2d5-11ea-84a2-b09af0ce8618.png)
-------------------------------------------------------------------------------------------
### For Channel Shuffle
--------------------------------------------------------------------------------------------------------
First time When I applied the ChannelShuffle
![image](https://user-images.githubusercontent.com/41751718/87155600-d75ad480-c2d8-11ea-9538-851034ffebb7.png)

--------------------------------------------------------------------------------------------------------
Second time when I applied the channel shuffle
![image](https://user-images.githubusercontent.com/41751718/87155107-015fc700-c2d8-11ea-88fa-21a01f12451b.png)

**Comment by pritul2** [comment]
Inconsistent behaviour

**Comment by wjacobward** [comment]
Can you describe the behavior you expect, because this looks correct to me. The first argument is a probability that the augmentation is applied, so I would expect iaa.Fliplr(0.5) to flip an image (on average) half of the time. If you would like an augmentation to be always applied, call it like you did in your third instance with the 'p' argument set to 1.

If instead you would like to apply augmentations randomly, but repeatably (so that you get the same augmentations applied to the same images every time you run a script), look into the 'seed' argument of the augmentation functions.
