### ISSUE TITLE
What is the "parents" parameter?

### ISSUE THREAD

**Issue by SarthakYadav** [aleju/imgaug#8]
Can you tell me the meaning of this parameter?? It's almost everywhere

Also. Keypoints_on_images seems to be a list object. Are individual keypoints list objects themselves? Or numpy array?

**Comment by aleju** [comment]
parents is passed mainly to _augment_images in order to indicate the chain of parent augmenters that have lead to that augmenter being applied. E.g. in something like `Sequential(Sometimes(Fliplr))`, Fliplr should get [Sequential, Sometimes] as parents. The variable is mainly used for the hooks in order to make it possible to deactivate augmenters based on their parents.

`KeypointsOnImage` is a class that contains objects of type `Keypoint`, which mostly just contain xy-values. `keypoints_on_images` is a list of `KeypointsOnImage` objects. I used objects in order to avoid confusion and errors related to exact numpy formats (e.g. shape (N,2) vs (N*2,) or xy vs yx format).

**Comment by SarthakYadav** [comment]
Ok. Got that.
