### ISSUE TITLE
Tips for being Memory Efficient 

### ISSUE THREAD

**Issue by pGit1** [aleju/imgaug#83]
This library is amazing! Do you have any tips for being memory efficient?

In my case I augment an image set of abut 300 images which after augmenation turns into about 21K images but all 21k are stored in memory. Is there a way to do this without it being stored in memory but still able to visualize the augmentations and use down stream for modelling purposes?

**Comment by aleju** [comment]
Not sure what you mean here with visualization?
Usually the library expects you to augment images batch by batch, so that your memory only has to be able to handle one batch of images at a time. That 21k number sounds like you are pre-generating lots of augmented images before starting the training. That is bound to consume lots of RAM and the library can't really do anything about it. Your options would be to change your code to augment every batch on the fly or to save the 21k images and dynamically load them per batch from the filesystem (this will consume lots of space and potentially be slow) or to compress the 21k images to JPEG in memory and then decompress them per batch (this will introduce JPEG compression artifacts and might not save much space for small images).

**Comment by pGit1** [comment]
Awesome that makes sense. I am indeed doing this 

>  sounds like you are pre-generating lots of augmented images before starting the training

and that is causing the issue. I am using the augment_image**s** command and doing it multiple times until I get to the 20K number. When you say "augment every batch on the fly, how to do this"? With a generator or something else?

**Comment by aleju** [comment]
> When you say "augment every batch on the fly, how to do this"? With a generator or something else?

Sample a batch of e.g. 64 images from your dataset, then apply `augment_images()` to these 64 images, then train (one forward-backward pass) on the 64 augmented images, then repeat from the start.

> what I mean by visualization I pass the augmented array to ia.draw_grid(img_array,row,col)

You feed the whole 20k images into `draw_grid()`?

> I am looking at the readme and I am not sure if my question is answered or not. I have a list of 16 augmenters, and I want all sample images to be augmented by them at least twice during training process or more. Right now I am looping over the list and using augmenter.augment_images() command twice for each augenter in my list and creating a new array of augmented images. This is super memory intensive so I am trying to change my process. All of the readme's uses ia.sequential but I dont want to do sequnetial augmentation as that would be too strong. Any thoughts?

If your only aim here is to avoid too strong augmentations by reducing the number of applied augmenters per image, then you can simply use `SomeOf(N, augmenters)` instead of `Sequential()`. E.g. something like `SomeOf(2, [Affine(...), AdditiveGaussianNoise(...), Dropout(...), ...])` will always pick exactly two of the provided augmenters and apply them to the image batch, while the other augmenters are ignored. You can also set `N` to `(1,3)` to pick at least one and up to three augmenters per batch.

**Comment by pGit1** [comment]
> You feed the whole 20k images into draw_grid()?
No I want clear. Just a sample of those images.

>  If your only aim here is to avoid too strong augmentations by reducing the number of applied augmenters per image, then you can simply use `SomeOf(N, augmenters)` instead of `Sequential()`

Yes!! I discovered SomeOf yesterday and have been fiddling with it ever since. I am training with it and and even toying with throwing it in a generator. Will keep you posted on results. AWESOME library.

**Comment by pGit1** [comment]
Closing for now. Thanks for your help as usual.

**Comment by abarajithan11** [comment]
I have memory error issue even with a batch size of 32.

I'm trying to setup an input pipeline for yolo object detector. For every batch I have an image_batch numpy array (32,416,416,3). I set up a augumentation pipeline of resize, flip, noise...etc. (note: I am not setting up a seq(list) in advance and using it. I am updating the list for every batch) When i run this, i get an error:

Memory Error: np.zeros(output_shape, images.dtype) at Resize()

How can i solve this?

**Comment by pGit1** [comment]
You images are HUGE! So lower your mini-batch size (by powers of 2 so try
16, 8, 4, 2) or decrease the resolution of your images. It sounds like you
dont even have enough RAM to deal with your images.

Steps:

1. Determine how much RAM you have
2. Create a dataset of  x = np.zeros(1,416,416,3)
3. Compute bytes by x.nbytes. Divide 32*x.nbytes/1024/1024/1024 to convert
to gigabytes and compare that to the ram you have. If this number exceeds
your RAM then lower the 32 in the formula until it is below your ram

**Comment by aleju** [comment]
> Memory Error: np.zeros(output_shape, images.dtype) at Resize()

Please post the full stack trace.

One copy of a batch of 32 416x416x3 images in uint8 should require about 16MByte of RAM. That will be needed a few more times if you don't use Sequential (at least one copy per augmenter). How much RAM do you have? Is it possible that your RAM is already mostly used up before even starting the augmentation process? Are you preloading the whole dataset into RAM?

**Comment by abarajithan11** [comment]
I have 8gb ram. I use tfrecords read through a generator to read one
example at a time.
