### ISSUE TITLE
Make the bounding box more tighten for the object after image rotation

### ISSUE THREAD

**Issue by panovr** [aleju/imgaug#90]
I use this code for image and bounding box rotation:
   ```
    ia.seed(1)
    image = # read image
    bbs = ia.BoundingBoxesOnImage(
        [ia.BoundingBox(x1=95, y1=52, x2=250, y2=245)],
        shape=image.shape)

    seq = iaa.Sequential([
        iaa.Multiply((1.2, 1.5)), # change brightness, doesn't affect BBs
        iaa.Affine(
            rotate=45.0,
        )
    ])

    seq_det = seq.to_deterministic()

    image_aug = seq_det.augment_images([image])[0]
    bbs_aug = seq_det.augment_bounding_boxes([bbs])[0]
```
The results are:
![Image](http://cs2.swfu.edu.cn/~zyl/rotation.png)

As you can see, the bounding box became larger after rotation.

Is it posibble to make the bounding box more tighten for the object after image rotation?

**Comment by aleju** [comment]
This is a known problem. The bounding box augmentation is based on augmenting the corner points of the bounding boxes, then drawing a new bounding box around these corners. That can lead to badly fitting bounding boxes, especially after rotations. The image below shows where that effect comes from:

![bb_aug](https://user-images.githubusercontent.com/11698516/34915123-6b34be44-f920-11e7-83fd-0726095317cf.jpg)

Currently, I can't really think of a good way to fix this. Arbitrarily shrinking bounding boxes risks losing legitimate parts of them, e.g. for thin and high bounding boxes.

**Comment by panovr** [comment]
It makes sense, and thanks for the explanation.

**Comment by kmsravindra** [comment]
@panovr, I had a similar issue and was searching and landed here...As per fast.ai, this is the observation that was made and found it relevant. So just wanted to share if someone lands here like me...

If the object occupied the corners of the original bounding box, your new bounding box needs to be bigger after the image rotates. So you must be careful of not doing too higher rotations with bounding boxes because there is not enough information for them to stay accurate. So here, we do maximum of 3 degree rotation to avoid this problem [.](https://www.youtube.com/watch?v=0frKXR-2PBY&feature=youtu.be&t=9m14s)

**Comment by cortical-iv** [comment]
@kmsravindra that video is super helpful thanks! There is just no way around this: you don't know a priori where the important stuff is in the bounding box, so it just has to grow in size. That's why it is safest (and easiest) to stick with flips instead of rotations.

**Comment by rra94** [comment]
Hey, I found this exact same issue see the figure attached. Did anyone come up with a better solution? Please help!


![image](https://user-images.githubusercontent.com/5424122/98276640-446b3780-1f64-11eb-8cc3-ee4b3f4a6886.png)
